apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa-secret
  namespace: support-tools
  annotations:
    kubernetes.io/service-account.name: rundeck-k8s-sa
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-role
rules:
  - apiGroups:
      - "*"
    resources:
      # Grant only CRUD operation in Pods and Jobs resources
      - "pods"
      - "pods/log"
      - "jobs"
      - "jobs/status"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
