apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ .Release.Name }}-realm-properties-secret
    namespace: {{ .Release.Namespace }}
data:
    realm.properties: {{ .Values.app.secrets.realm_properties }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ .Release.Name }}-secret
    namespace: {{ .Release.Namespace }}
data:
    ENC_PASSWORD: {{ .Values.app.secrets.enc_password }}
    RUNDECK_DATABASE_PASSWORD: {{ .Values.app.secrets.database_user }}
    RUNDECK_DATABASE_USERNAME: {{ .Values.app.secrets.database_password }}
    
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ .Release.Name }}-ssh-key
    namespace: {{ .Release.Namespace }}
stringdata:
    ssh-key: {{ .Values.app.secrets.ssh_key}}